### ISSUE TITLE
Version 5 Release?

### ISSUE THREAD

**Issue by jalakoo** [IBAnimatable/IBAnimatable#513]
Readme mentions using 5.x tagged releases with Xcode 9. But there are no such tagged releases or branches at this time. Are these planned releases or are they located in a different repo?

**Comment by SD10** [comment]
@jalakoo Sorry! We haven't had time to push a 5.0 release! We should be doing this ASAP.
For the meantime you can just use `pod IBAnimatable` which will pull the latest code from `master` and has Swift 4 & Xcode 9 support.

**Comment by jalakoo** [comment]
Thanks @SD10, I'll just patiently wait as I'm one of the few non-Cocoapod fans out there.

For anyone else in the same boat: I'm temporarily using the source files in a framework target with Swift 3.2 specified. That way the rest of my project can still use Swift 4.

**Comment by justbane** [comment]
I am not seeing a 5.x version available in Cocoa Pods... how might we pull that down?

Also changing the swift version in the pod target reduces the number of errors save for one...

/Pods/IBAnimatable/Sources/Protocols/Designable/PlaceholderDesignable.swift:23:84: Type 'NSAttributedStringKey' (aka 'NSString') has no member 'foregroundColor'

**Comment by jalakoo** [comment]
If not using Swift 4, you will have to replace NSAttributedStringKey.foregroundColor with NSForegroundColorAttributeName.  Though that may start other issues, because the old attribute name was a string constant and the new .foregroundColor is an enum.

**Comment by gkye** [comment]
Hey @justbane, the pod for 5.0 hasn’t been released yet, you can use 
`pod 'IBAnimatable', :git => 'https://github.com/IBAnimatable/IBAnimatable.git'` to directly fetch from the master branch for now

**Comment by JakeLin** [comment]
We have released version 5 https://cocoapods.org/pods/IBAnimatable 🎉 🎉 🎉 

Please let us know if you have any problem, thanks.

**Comment by ReFiRnE** [comment]
Type 'String' has no member 'foregroundColor'. still appearing for me, even though I have 5 version and I set compiler language Swift 4.0

**Comment by ignivashiju** [comment]
Hi team, 

In XCode 9.3, i am not able to use IBAnimatable pods. It throw errors. Please check the attached screenshot for same. I am using version swift 4.1. Any suggestions?


![screen shot 2018-04-20 at 1 06 46 pm](https://user-images.githubusercontent.com/16932010/39036843-68455bfe-449c-11e8-8adb-f5e72efcde95.png)

**Comment by SD10** [comment]
@ignivashiju Can you please open a separate issue to track this?

**Comment by ignivashiju** [comment]
sure!!
